# Homebrew formula for the Provenly CLI (`prov`).
# Auto-generated by the release workflow for v0.139.
class Prov < Formula
  desc "Provenly CLI - developer intelligence at your fingertips"
  homepage "https://provenly.live"
  version "0.139"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.139/provenly-darwin-arm64"
      sha256 "7c47e3ae0aa3e141901a189e6aaf5c9fa0fee2da893975cbbce51be45744236c"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.139/provenly-darwin-amd64"
      sha256 "9474244ca4c84d60ee2ffd00c96bdfb32e45a9cda1b5876311f7723d692dd313"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.139/provenly-linux-arm64"
      sha256 "a58872f4db45a912859c5ff21f4d14e11f0464bc15763c40c00eb7b2606d7a51"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.139/provenly-linux-amd64"
      sha256 "878f69321c25c422e0c5460e72990e1c49a7b3c332fe0ed1c8dabc2d19069b72"
    end
  end

  def install
    bin.install Dir["provenly-*"].first => "prov"
  end

  test do
    assert_match "prov version", shell_output("#{bin}/prov version")
  end
end
