# Homebrew formula for the Provenly CLI (`prov`).
# Auto-generated by the release workflow for v0.1.00.
class Prov < Formula
  desc "Provenly CLI - developer intelligence at your fingertips"
  homepage "https://provenly.live"
  version "0.1.00"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.1.00/provenly-darwin-arm64"
      sha256 "b64de78b45a3c2658a6699d92d0214a71a41fa0b257efdb59b79437769aaade1"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.1.00/provenly-darwin-amd64"
      sha256 "ed418e9ba2d29083dc3a9ec44996dbf322515611598bee49f2b4f92b486298b7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.1.00/provenly-linux-arm64"
      sha256 "fa690aa50da3e1b318489a25ff3a2139ef697b2956c439cc2bfdbec2117486d8"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.1.00/provenly-linux-amd64"
      sha256 "2cab475c0ab94838f6d43f1a74d5d5900a05bacdcc5ceb43428c20f95f4d6197"
    end
  end

  def install
    bin.install Dir["provenly-*"].first => "prov"
  end

  test do
    assert_match "prov version", shell_output("#{bin}/prov version")
  end
end
