# Homebrew formula for the Provenly CLI (`prov`).
# Auto-generated by the release workflow for v0.1.221.
class Prov < Formula
  desc "Provenly CLI - developer intelligence at your fingertips"
  homepage "https://provenly.live"
  version "0.1.221"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.1.221/provenly-darwin-arm64"
      sha256 "911c64d4bf0e5711cedba698709321aad0968934fef9544475ec48470ae5a212"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.1.221/provenly-darwin-amd64"
      sha256 "bc5716d5158da20893433292b5292bbc60419114aff69c56d8445c1ab91ce6e7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/devup-io/prov/releases/download/v0.1.221/provenly-linux-arm64"
      sha256 "0d1ac553e733ae2c9a9bd1748839e945dabb16a7915854afae79a31d15e8c98b"
    end
    on_intel do
      url "https://github.com/devup-io/prov/releases/download/v0.1.221/provenly-linux-amd64"
      sha256 "9b7b91524c16281eb37a539e6d116df52a06061d54ec7bdc83e44238ad83ec89"
    end
  end

  def install
    bin.install Dir["provenly-*"].first => "prov"
  end

  test do
    assert_match "prov version", shell_output("#{bin}/prov version")
  end
end
